# Generated by Django 3.0.2 on 2020-01-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp1', '0002_auto_20200106_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat_field',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='long_field',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
